DROP TABLE IF EXISTS businesses;

CREATE TABLE businesses(
    id SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    phone VARCHAR(30) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NULL NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);